SaRaEcomAdmin/Controllers/ConfigurationController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using SaRaEcomAdmin.DAL;
using SaRaEcomAdmin.Models;
using System.IO;
using SaRaEcomAdmin.Utility;
using System;

namespace SaRaEcomAdmin.Controllers
{
    public class ConfigurationController : Controller
    {
        private readonly ConfigurationDal _objConfigurationDal = new ConfigurationDal();

        #region "Common"

        private string _strEmployeeId = "";
        private string _strHeadOfficeId = "";
        private string _strBranchOfficeId = "";

        public void LoadSession()
        {
            var auth = Session["authentication"] as AuthModel;

            if (auth != null)
            {
                _strEmployeeId = auth.EmployeeId;
                _strHeadOfficeId = auth.HeadOfficeId;
                _strBranchOfficeId = auth.BranchOfficeId;
            }
            else
            {
                string url = Url.Action("Index", "Auth");
                if (url != null) Response.Redirect(url);
            }
        }
        #endregion

        #region Slider

        public async Task<ActionResult> Slider(int? id)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            SliderModel model = new SliderModel();

            var objSliderModel = await _objConfigurationDal.GetSliderList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.SliderList = objSliderModel;

            if (id != null && id != 0)
            {
                model = await _objConfigurationDal.GetSlider((int)id, _strHeadOfficeId, _strBranchOfficeId);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveSlider(SliderModel objSliderModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                objSliderModel.UpdateBy = _strEmployeeId;
                objSliderModel.HeadOfficeId = _strHeadOfficeId;
                objSliderModel.BranchOfficeId = _strBranchOfficeId;

                string filePath = Server.MapPath("~/Files/Slider/");
                string vFileName = Guid.NewGuid().ToString();

                if (objSliderModel.SliderId == 0)
                {
                    if (objSliderModel.SliderImage != null)
                    {
                        var imageExtension = Path.GetExtension(objSliderModel.SliderImage.FileName);
                        if (imageExtension != null)
                        {
                            imageExtension = imageExtension.ToUpper();
                            if (imageExtension == ".JPG" || imageExtension == ".JPEG" || imageExtension == ".PNG")
                            {
                                string imagePath = filePath + objSliderModel.SliderImageSiring;
                                if (System.IO.File.Exists(imagePath))
                                {
                                    System.IO.File.Delete(imagePath);
                                }

                                filePath += vFileName;
                                filePath += imageExtension.ToLower();

                                objSliderModel.SliderImage.SaveAs(filePath);

                                objSliderModel.SliderImageSiring = vFileName + imageExtension.ToLower();
                                string strMessage = await _objConfigurationDal.SaveSlider(objSliderModel);
                                TempData["message"] = strMessage;
                            }
                            else
                            {
                                TempData["message"] = "Image Must be .JPG or .JPEG or .PNG";
                            }
                        }
                    }
                    else
                    {
                        TempData["message"] = "Image is required";
                    }
                }
                else
                {
                    var imageExtension = Path.GetExtension(objSliderModel.SliderImage?.FileName);
                    if (imageExtension != null)
                    {
                        imageExtension = imageExtension.ToUpper();
                        if (imageExtension == ".JPG" || imageExtension == ".JPEG" || imageExtension == ".PNG")
                        {
                            string imagePath = filePath + objSliderModel.SliderImageSiring;
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }

                            filePath += vFileName;
                            filePath += imageExtension.ToLower();

                            objSliderModel.SliderImage.SaveAs(filePath);

                            objSliderModel.SliderImageSiring = vFileName + imageExtension.ToLower();
                        }
                        else
                        {
                            TempData["message"] = "Image Must be .JPG or .JPEG or .PNG";
                            return RedirectToAction("Slider");
                        }
                    }
                    string strMessage = await _objConfigurationDal.SaveSlider(objSliderModel);
                    TempData["message"] = strMessage;
                }
            }
            return RedirectToAction("Slider");
        }

        public async Task<ActionResult> DeleteSlider(int id)
        {
            LoadSession();
            string message = await _objConfigurationDal.DeleteSlider(id, _strHeadOfficeId, _strBranchOfficeId);
            TempData["message"] = message;

            return RedirectToAction("Slider");
        }

        #endregion

        #region Offer

        public async Task<ActionResult> Offer(int? id)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            OfferModel model = new OfferModel();

            var objOfferModel = await _objConfigurationDal.GetOfferList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.SliderList = objOfferModel;

            if (id != null && id != 0)
            {
                model = await _objConfigurationDal.GetOffer((int)id, _strHeadOfficeId, _strBranchOfficeId);
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveOffer(OfferModel offerModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                offerModel.UpdateBy = _strEmployeeId;
                offerModel.HeadOfficeId = _strHeadOfficeId;
                offerModel.BranchOfficeId = _strBranchOfficeId;

                string filePath = Server.MapPath("~/Files/Offer/");
                string vFileName = Guid.NewGuid().ToString();

                if (offerModel.OfferId == 0)
                {
                    if (offerModel.OfferImage != null)
                    {
                        var imageExtension = Path.GetExtension(offerModel.OfferImage.FileName);
                        if (imageExtension != null)
                        {
                            imageExtension = imageExtension.ToUpper();
                            if (imageExtension == ".JPG" || imageExtension == ".JPEG" || imageExtension == ".PNG" || imageExtension == ".GIF")
                            {
                                string imagePath = filePath + offerModel.OfferImageSiring;
                                if (System.IO.File.Exists(imagePath))
                                {
                                    System.IO.File.Delete(imagePath);
                                }

                                filePath += vFileName;
                                filePath += imageExtension.ToLower();

                                offerModel.OfferImage.SaveAs(filePath);

                                offerModel.OfferImageSiring = vFileName + imageExtension.ToLower();
                                string strMessage = await _objConfigurationDal.SaveSlider(offerModel);
                                TempData["message"] = strMessage;
                            }
                            else
                            {
                                TempData["message"] = "Image Must be .JPG or .JPEG or .PNG of GIF";
                            }
                        }
                    }
                    else
                    {
                        TempData["message"] = "Image is required";
                    }
                }
                else
                {
                    var imageExtension = Path.GetExtension(offerModel.OfferImage?.FileName);
                    if (imageExtension != null)
                    {
                        imageExtension = imageExtension.ToUpper();
                        if (imageExtension == ".JPG" || imageExtension == ".JPEG" || imageExtension == ".PNG" || imageExtension == ".GIF")
                        {
                            string imagePath = filePath + offerModel.OfferImageSiring;
                            if (System.IO.File.Exists(imagePath))
                            {
                                System.IO.File.Delete(imagePath);
                            }

                            filePath += vFileName;
                            filePath += imageExtension.ToLower();

                            offerModel.OfferImage.SaveAs(filePath);

                            offerModel.OfferImageSiring = vFileName + imageExtension.ToLower();
                        }
                        else
                        {

SaRaEcomAdmin/Views/Configuration/Banner.cshtml
@using SaRaEcomAdmin.Models
@model SaRaEcomAdmin.Models.BannerModel
@{
    ViewBag.Title = "Banner";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var bannerModel = ViewBag.BannerList as List<BannerModel>;
}
<link rel="stylesheet" type="text/css" href="/Content/assets/bootstrap-fileinput/bootstrap-fileinput.css" />

<div class="page-head">
    <div class="page-title">
        <h1>Manage Banner</h1>
    </div>
</div>

<div class="row margin-top-10">
    <div class="col-md-12">
        <div class="portlet box green-haze">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Edit Banner
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                @using (Html.BeginForm("SaveBanner", "Configuration", FormMethod.Post, new { @class = "form-horizontal", role = "form", @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-body">
                        <div class="form-group margin-top-15">
                            @Html.LabelFor(c => c.BannerTitle, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.BannerTitle, new { @class = "form-control input-circle", @placeholder = "Banner Title" })
                                    @Html.ValidationMessageFor(c => c.BannerTitle)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.BannerDescription, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.BannerDescription, new { @class = "form-control input-circle", @placeholder = "Banner Description" })
                                    @Html.ValidationMessageFor(c => c.BannerDescription)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.BannerUrl, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.BannerUrl, new { @class = "form-control input-circle", @placeholder = "Banner Url" })
                                    @Html.ValidationMessageFor(c => c.BannerUrl)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.DisplayOrder, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.DisplayOrder, new { @class = "form-control input-circle", @placeholder = "Display Order", @type = "number" })
                                    @Html.ValidationMessageFor(c => c.DisplayOrder)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(c => c.BannerImage, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="show-image-div show-image-divm">
                                    <a data-target="#imageModal" data-toggle="modal">
                                        @if (Model.BannerImageSiring != null)
                                        {
                                            <img id="showImage" class="show-prev-img show-prev-imgm" src="@Path.Combine("/Files/Banner/", Model.BannerImageSiring)" style="width: 100px; height: 100px; border: 1px solid #ddd; padding: 3px;">
                                            @Html.HiddenFor(c => c.BannerImageSiring)
                                        }
                                        else
                                        {
                                            <img id="showImage" class="show-prev-img show-prev-imgm" style="width: 100px; height: 100px; border: 1px solid #ddd; padding: 3px;">
                                        }
                                    </a>
                                </div>
                                <div class="fileUpload fileUploadm btn btn-sm btn-primary btn-image btn-imagem">
                                    <span><i class="fa fa-picture-o"></i> Choose Image</span>
                                    @Html.TextBoxFor(m => m.BannerImage, "", new { @type = "file", @class = "imageUpload imageUploadm" })
                                </div>
                                @Html.ValidationMessageFor(c => c.BannerImage)
                                <br />
                                <br />
                                <p><span class="label label-danger">NOTE!</span> Banner can't be Added, Only Edit is Available...</p>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-right">
                                @Html.HiddenFor(c => c.BannerId)
                                @if (Model.BannerId != 0)
                                {
                                    <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save</button>
                                }
                                else
                                {
                                    <button class="btn btn-success btn-lg btn-circle" type="submit" disabled="disabled"><i class="fa fa-save"></i> Save</button>
                                }                                
                                @Html.ActionLink(" Clear", "Banner", "Configuration", new { id = 0 }, new { @class = "btn btn-info btn-lg btn-circle fa fa-times" })
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Slider Lists
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Banner Title</th>
                                <th>Banner Description</th>
                                <th>Banner Url</th>
                                <th>Display Order</th>
                                <th>Banner Image</th>
                                <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (bannerModel != null && bannerModel.Count > 0)
                            {
                                int counter = 1;
                                foreach (var data in bannerModel)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>@data.BannerTitle</td>
                                        <td>@data.BannerDescription</td>
                                        <td>@data.BannerUrl</td>
                                        <td>@data.DisplayOrder</td>
                                        <td><img style="width: 50px;height: 50px;border: 1px solid #ddd;padding: 3px;" src="@Path.Combine("/Files/Banner/", data.BannerImageSiring)" /></td>
                                        <td class="text-center">
                                            @Html.ActionLink(" Edit", "Banner", "Configuration", new { id = data.BannerId }, new { @class = "btn btn-success btn-xs fa fa-edit" })
                                        </td>
                                    </tr>
                                    counter = counter + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="7" class="text-center">No Data Found</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" src="/Content/assets/bootstrap-fileinput/bootstrap-fileinput.js"></script>
<script>
    function newReadUrl(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(input).parents('.fileUploadm').siblings('.show-image-divm').find('.show-prev-imgm').attr('src', e.target.result);
                $("#displayImage").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).on('change', '.imageUploadm', function () {
        newReadUrl(this);
    });
    jQuery(document).ready(function () {
        //ComponentsFormTools.init();
        @{
            if (!string.IsNullOrWhiteSpace(@ViewBag.Message))
            {
                <text>
                    var message = '@ViewBag.message';


                    toastr.options = {
                        "closeButton": true,
                        "debug": false,
                        "positionClass": "toast-top-center",
                        "onclick": null,
                        "showDuration": "1000",
                        "hideDuration": "1000",
                        "timeOut": "5000",
                        "extendedTimeOut": "1000",
                        "showEasing": "swing",
                        "hideEasing": "linear",
                        "showMethod": "fadeIn",
                        "hideMethod": "fadeOut"
                    }
                    toastr.info(message, 'Information!');
                </text>
            }
        }
    });

</script>

SaRaEcomAdmin/Views/Configuration/HomePagePopup.cshtml
@using SaRaEcomAdmin.Models
@model SaRaEcomAdmin.Models.PopupModel
@{
    ViewBag.Title = "Home Page Popup";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var popupModel = ViewBag.PopupList as List<PopupModel>;
}
<link rel="stylesheet" type="text/css" href="/Content/assets/bootstrap-fileinput/bootstrap-fileinput.css" />

<div class="page-head">
    <div class="page-title">
        <h1>Manage Home Page Popup</h1>
    </div>
</div>

<div class="row margin-top-10">
    <div class="col-md-12">
        <div class="portlet box green-haze">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Popup
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                @using (Html.BeginForm("SaveHomePagePopup", "Configuration", FormMethod.Post, new { @class = "form-horizontal", role = "form", @enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-body">
                        <div class="form-group margin-top-15">
                            @Html.LabelFor(c => c.PopupName, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.PopupName, new { @class = "form-control input-circle", @placeholder = "Slider Title" })
                                    @Html.ValidationMessageFor(c => c.PopupName)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.IsActive, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                    @Html.CheckBoxFor(c => c.IsActive, new { @class = "checker", @placeholder = "Slider Url" })
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group ">
                            @Html.LabelFor(c => c.PopupImage, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="show-image-div show-image-divm">
                                    <a data-target="#imageModal" data-toggle="modal">
                                        @if (Model.PopupImageSiring != null)
                                        {
                                            <img id="showImage" class="show-prev-img show-prev-imgm" src="@Path.Combine("/Files/Popup/", Model.PopupImageSiring)" style="width: 100px; height: 100px; border: 1px solid #ddd; padding: 3px;">
                                            @Html.HiddenFor(c => c.PopupImageSiring)
                                        }
                                        else
                                        {
                                            <img id="showImage" class="show-prev-img show-prev-imgm" style="width: 100px; height: 100px; border: 1px solid #ddd; padding: 3px;">
                                        }
                                    </a>
                                </div>
                                <div class="fileUpload fileUploadm btn btn-sm btn-primary btn-image btn-imagem">
                                    <span><i class="fa fa-picture-o"></i> Choose Image</span>
                                    @Html.TextBoxFor(m => m.PopupImage, "", new { @type = "file", @class = "imageUpload imageUploadm" })
                                </div>
                                @Html.ValidationMessageFor(c => c.PopupImage)
                                <br />
                                <br />
                                <p><span class="label label-danger">NOTE!</span> Image must be jpg or jpeg or png, Ratio 000*000</p>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-right">
                                @Html.HiddenFor(c => c.PopupId)
                                <button class="btn btn-success btn-lg btn-circle" type="submit"><i class="fa fa-save"></i> Save</button>
                                @Html.ActionLink(" Clear", "HomePagePopup", "Configuration", new { id = 0 }, new { @class = "btn btn-info btn-lg btn-circle fa fa-times" })
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Popup Lists
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-bordered">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Popup Name</th>
                                <th>Active Status</th>
                                <th>Slider Image</th>
                                <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (popupModel != null && popupModel.Count > 0)
                            {
                                int counter = 1;
                                foreach (var data in popupModel)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>@data.PopupName</td>
                                        <td>@data.IsActive</td>
                                        <td><img style="width: 50px;height: 50px;border: 1px solid #ddd;padding: 3px;" src="@Path.Combine("/Files/Popup/", data.PopupImageSiring)" /></td>
                                        <td class="text-center">
                                            @Html.ActionLink(" Edit", "HomePagePopup", "Configuration", new { id = data.PopupId }, new { @class = "btn btn-success btn-xs fa fa-edit" }) ||
                                            @Html.ActionLink(" Delete", "DeleteHomePagePopup", "Configuration", new { id = data.PopupId }, new { @class = "btn btn-danger btn-xs fa fa-trash-o" })
                                        </td>
                                    </tr>
                                    counter = counter + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="6" class="text-center">No Data Found</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" src="/Content/assets/bootstrap-fileinput/bootstrap-fileinput.js"></script>
<script>
    function newReadUrl(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
                $(input).parents('.fileUploadm').siblings('.show-image-divm').find('.show-prev-imgm').attr('src', e.target.result);
                $("#displayImage").attr('src', e.target.result);
            }
            reader.readAsDataURL(input.files[0]);
        }
    }

    $(document).on('change', '.imageUploadm', function () {
        newReadUrl(this);
    });
    jQuery(document).ready(function () {
        @{
            if (!string.IsNullOrWhiteSpace(@ViewBag.Message))
            {
                <text>
                    var message = '@ViewBag.message';


                    toastr.options = {
                        "closeButton": true,
                        "debug": false,
                        "positionClass": "toast-top-center",
                        "onclick": null,
                        "showDuration": "1000",
                        "hideDuration": "1000",
                        "timeOut": "5000",
                        "extendedTimeOut": "1000",
                        "showEasing": "swing",
                        "hideEasing": "linear",
                        "showMethod": "fadeIn",
                        "hideMethod": "fadeOut"
                    }
                    toastr.info(message, 'Information!');
                </text>
            }
        }
    });

</script>