SaRaEcomAdmin/Controllers/SetupController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using SaRaEcomAdmin.DAL;
using SaRaEcomAdmin.Models;
using SaRaEcomAdmin.Utility;

namespace SaRaEcomAdmin.Controllers
{
    public class SetupController : Controller
    {
        private readonly SetupDal _objSetupDal = new SetupDal();

        #region "Common"

        private string _strEmployeeId = "";
        private string _strHeadOfficeId = "";
        private string _strBranchOfficeId = "";

        public void LoadSession()
        {
            var auth = Session["authentication"] as AuthModel;

            if (auth != null)
            {
                _strEmployeeId = auth.EmployeeId;
                _strHeadOfficeId = auth.HeadOfficeId;
                _strBranchOfficeId = auth.BranchOfficeId;
            }
            else
            {
                string url = Url.Action("Index", "Auth");
                if (url != null) Response.Redirect(url);
            }
        }
        #endregion

        #region "Category"
        public async Task<ActionResult> Category(int? id)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            CategoryModel model = new CategoryModel();

            var objCategoryModel = await _objSetupDal.GetCategoryList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.CategoryList = objCategoryModel;

            if (id != null && id != 0)
            {
                model = await _objSetupDal.GetCategory((int) id, _strHeadOfficeId, _strBranchOfficeId);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveCategory(CategoryModel objCategoryModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                objCategoryModel.UpdateBy = _strEmployeeId;
                objCategoryModel.HeadOfficeId = _strHeadOfficeId;
                objCategoryModel.BranchOfficeId = _strBranchOfficeId;

                string strMessage = await _objSetupDal.SaveCategory(objCategoryModel);
                TempData["message"] = strMessage;
            }
            return RedirectToAction("Category");
        }

        public async Task<ActionResult> DeleteCategory(int id)
        {
            LoadSession();
            string message = await _objSetupDal.DeleteCategory(id, _strHeadOfficeId, _strBranchOfficeId);
            TempData["message"] = message;

            return RedirectToAction("Category");
        }
        #endregion

        #region SubCategory
        public async Task<ActionResult> SubCategory(int? categoryId, int? subCategoryId)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            SubCategoryModel model = new SubCategoryModel();

            var objSubCategoryModels = await _objSetupDal.GetSubCategoryList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.SubCategoryList = objSubCategoryModels;

            if (categoryId != null && categoryId != 0 && subCategoryId != null && subCategoryId != 0)
            {
                model = await _objSetupDal.GetSubCategory((int)categoryId, (int)subCategoryId, _strHeadOfficeId, _strBranchOfficeId);
            }

            ViewBag.CategoryList = UtilityClass.GetSelectListByDataTable(_objSetupDal.GetCategoryListDropdown(), "CATEGORY_ID", "CATEGORY_NAME");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveSubCategory(SubCategoryModel objSubCategoryModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                objSubCategoryModel.UpdateBy = _strEmployeeId;
                objSubCategoryModel.HeadOfficeId = _strHeadOfficeId;
                objSubCategoryModel.BranchOfficeId = _strBranchOfficeId;

                string strMessage = await _objSetupDal.SaveSubCategory(objSubCategoryModel);
                TempData["message"] = strMessage;
            }
            return RedirectToAction("SubCategory");
        }

        public async Task<ActionResult> DeleteSubCategory(int categoryId, int subCategoryId)
        {
            LoadSession();
            string message = await _objSetupDal.DeleteSubCategory(categoryId, subCategoryId, _strHeadOfficeId, _strBranchOfficeId);
            TempData["message"] = message;

            return RedirectToAction("SubCategory");
        }
        #endregion

        #region SubSubCategory
        public async Task<ActionResult> SubSubCategory(int? categoryId, int? subCategoryId, int? subSubCategoryId)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            SubSubCategoryModel model = new SubSubCategoryModel();

            var objSubSubCategoryModels = await _objSetupDal.GetSubSubCategoryList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.SubSubCategoryList = objSubSubCategoryModels;

            if (categoryId != null && categoryId != 0 && subCategoryId != null && subCategoryId != 0 && subSubCategoryId != null && subSubCategoryId != 0)
            {
                model = await _objSetupDal.GetSubSubCategory((int)categoryId, (int)subCategoryId, (int)subSubCategoryId, _strHeadOfficeId, _strBranchOfficeId);
                ViewBag.SubCategoryList = UtilityClass.GetSelectListByDataTable(_objSetupDal.GetSubCategoryListDropdown((int)categoryId), "SUB_CATEGORY_ID", "SUB_CATEGORY_NAME");
            }

            ViewBag.CategoryList = UtilityClass.GetSelectListByDataTable(_objSetupDal.GetCategoryListDropdown(), "CATEGORY_ID", "CATEGORY_NAME");

            return View(model);
        }

        public JsonResult GetSubCategoryList(int categoryId)
        {
            var list = UtilityClass.GetSelectListByDataTable(_objSetupDal.GetSubCategoryListDropdown(categoryId), "SUB_CATEGORY_ID", "SUB_CATEGORY_NAME");
            return Json(list, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveSubSubCategory(SubSubCategoryModel objSubSubCategoryModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                objSubSubCategoryModel.UpdateBy = _strEmployeeId;
                objSubSubCategoryModel.HeadOfficeId = _strHeadOfficeId;
                objSubSubCategoryModel.BranchOfficeId = _strBranchOfficeId;

                string strMessage = await _objSetupDal.SaveSubSubCategory(objSubSubCategoryModel);
                TempData["message"] = strMessage;
            }
            return RedirectToAction("SubSubCategory");
        }

        public async Task<ActionResult> DeleteSubSubCategory(int categoryId, int subCategoryId, int subSubCategoryId)
        {
            LoadSession();
            string message = await _objSetupDal.DeleteSubSubCategory(categoryId, subCategoryId, subSubCategoryId, _strHeadOfficeId, _strBranchOfficeId);
            TempData["message"] = message;

            return RedirectToAction("SubSubCategory");
        }
        #endregion

        #region "Size"
        public async Task<ActionResult> Size(int? id)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            SizeModel model = new SizeModel();

            var objSizeModel = await _objSetupDal.GetSizeList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.SizeList = objSizeModel;

            if (id != null && id != 0)
            {
                model = await _objSetupDal.GetSize((int)id, _strHeadOfficeId, _strBranchOfficeId);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveSize(SizeModel objSizeModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {
                objSizeModel.UpdateBy = _strEmployeeId;
                objSizeModel.HeadOfficeId = _strHeadOfficeId;
                objSizeModel.BranchOfficeId = _strBranchOfficeId;

                string strMessage = await _objSetupDal.SaveSize(objSizeModel);
                TempData["message"] = strMessage;
            }
            return RedirectToAction("Size");
        }

        public async Task<ActionResult> DeleteSize(int id)
        {
            LoadSession();
            string message = await _objSetupDal.DeleteSize(id, _strHeadOfficeId, _strBranchOfficeId);
            TempData["message"] = message;

            return RedirectToAction("Size");
        }
        #endregion

        #region "Ratio"
        public async Task<ActionResult> Ratio(int? id)
        {
            ModelState.Clear();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.message = TempData["message"];
            }

            LoadSession();
            RatioModel model = new RatioModel();

            var objRatioModel = await _objSetupDal.GetRatioList(_strHeadOfficeId, _strBranchOfficeId);
            ViewBag.RatioList = objRatioModel;

            if (id != null && id != 0)
            {
                model = await _objSetupDal.GetRatio((int)id, _strHeadOfficeId, _strBranchOfficeId);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SaveRatio(RatioModel ratioModel)
        {
            LoadSession();
            if (ModelState.IsValid)
            {

SaRaEcomAdmin/Views/Setup/Category.cshtml
@using SaRaEcomAdmin.Models
@model SaRaEcomAdmin.Models.CategoryModel
@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var categoryModel = ViewBag.CategoryList as List<CategoryModel>;
}

<div class="page-head">
    <div class="page-title">
        <h1>Manage Category</h1>
    </div>
</div>

<div class="row margin-top-10">
    <div class="col-md-12">
        <div class="portlet box green-haze">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Category
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                @using (Html.BeginForm("SaveCategory", "Setup", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-body">
                        <div class="form-group">
                            @Html.LabelFor(c => c.CategoryName, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.CategoryName, new { @class = "form-control input-circle", @placeholder = "Category Name" })
                                    @Html.ValidationMessageFor(c => c.CategoryName)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.DisplayOrder, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-list-ol"></i>
                                    @Html.TextBoxFor(c => c.DisplayOrder, new { @class = "form-control input-circle", @placeholder = "Display Order", @type = "number" })
                                    @Html.ValidationMessageFor(c => c.DisplayOrder)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-right">
                                @Html.HiddenFor(c => c.CategoryId)
                                <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save</button>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Category Lists
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="categoryTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Category Name</th>
                                <th>Display Order</th>
                                <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (categoryModel != null && categoryModel.Count != 0)
                            {
                                int counter = 1;
                                foreach (var data in categoryModel)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>@data.CategoryName</td>
                                        <td>@data.DisplayOrder</td>
                                        <td class="text-center">
                                            @Html.ActionLink(" Edit", "Category", "Setup", new { id = data.CategoryId }, new { @class = "btn btn-success fa fa-edit" }) ||
                                            @Html.ActionLink("Delete", "DeleteCategory", "Setup", new { id = data.CategoryId }, new { @class = "btn btn-danger" })
                                        </td>
                                    </tr>
                                    counter = counter + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="4" class="text-center">No Data Found</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jqueryval")

<script>
    jQuery(document).ready(function () {

        var table = $("#categoryTable").dataTable();

        @{
        if (!string.IsNullOrWhiteSpace(@ViewBag.Message))
        {
        <text>
        var message = '@ViewBag.message';
                

        toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "positionClass": "toast-top-center",
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
        }
        toastr.info(message, 'Information!');
        </text>
        }
     }
    });
    
</script>

SaRaEcomAdmin/Views/Setup/Color.cshtml
@using SaRaEcomAdmin.Models
@model SaRaEcomAdmin.Models.ColorModel
@{
    ViewBag.Title = "Color";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var colorModel = ViewBag.ColorList as List<ColorModel>;
}
<link href="/Content/Assets/jquery-minicolors/jquery.minicolors.css" rel="stylesheet" type="text/css" />

<div class="page-head">
    <div class="page-title">
        <h1>Manage Color</h1>
    </div>
</div>

<div class="row margin-top-10">
    <div class="col-md-12">
        <div class="portlet box green-haze">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Color
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                @using (Html.BeginForm("SaveColor", "Setup", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-body">
                        <div class="form-group margin-top-15">
                            @Html.LabelFor(c => c.ColorName, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.ColorName, new { @class = "form-control input-circle", @placeholder = "Color Name" })
                                    @Html.ValidationMessageFor(c => c.ColorName)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(c => c.ColorCode, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                @*<input type="text" id="wheel-demo" class="form-control demo" data-control="wheel" value="#ff99ee">*@
                                @Html.TextBoxFor(c => c.ColorCode, new { @class = "form-control demo", @placeholder = "Color Code", data_control = "wheel", autocomplete = "off" })
                                @Html.ValidationMessageFor(c => c.ColorCode)
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-right">
                                @Html.HiddenFor(c => c.ColorId)
                                <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save</button>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Color Lists
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="colorTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Color Name</th>
                                <th>Color</th>
                                <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (colorModel != null && colorModel.Count > 0)
                            {
                                int counter = 1;
                                foreach (var data in colorModel)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>@data.ColorName</td>
                                        <td><div style="border-radius: 50%; background-color: @data.ColorCode; width: 30px; height: 30px;"></div></td>
                                        <td class="text-center">
                                            @Html.ActionLink(" Edit", "Color", "Setup", new { id = data.ColorId }, new { @class = "btn btn-success fa fa-edit" }) ||
                                            @Html.ActionLink(" Delete", "DeleteColor", "Setup", new { id = data.ColorId }, new { @class = "btn btn-danger fa fa-trash-o" })
                                        </td>
                                    </tr>
                                    counter = counter + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="3" class="text-center">No Data Found</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="/Content/Assets/bootstrap-selectsplitter/bootstrap-selectsplitter.min.js" type="text/javascript"></script>
<script src="/Content/Assets/jquery-minicolors/jquery.minicolors.min.js" type="text/javascript"></script>
<script src="/Scripts/components-form-tools2.js"></script>

@Scripts.Render("~/bundles/jqueryval")

<script>
    jQuery(document).ready(function () {
        ComponentsFormTools2.init();
        var table = $("#colorTable").dataTable();
        @{
        if (!string.IsNullOrWhiteSpace(@ViewBag.Message))
        {
        <text>
        var message = '@ViewBag.message';


        toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "positionClass": "toast-top-center",
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
        }
        toastr.info(message, 'Information!');
        </text>
        }
     }
    });

</script>

SaRaEcomAdmin/Views/Setup/Fabric.cshtml
@using SaRaEcomAdmin.Models
@model SaRaEcomAdmin.Models.FabricModel
@{
    ViewBag.Title = "Fabric";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var fabricModel = ViewBag.FabricList as List<FabricModel>;
}

<div class="page-head">
    <div class="page-title">
        <h1>Manage Fabric</h1>
    </div>
</div>

<div class="row margin-top-10">
    <div class="col-md-12">
        <div class="portlet box green-haze">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Add Fabric
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                @using (Html.BeginForm("SaveFabric", "Setup", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-body">
                        <div class="form-group margin-top-15">
                            @Html.LabelFor(c => c.FabricName, new { @class = "col-md-3 control-label" })
                            <div class="col-md-6">
                                <div class="input-icon">
                                    <i class="fa fa-text-width"></i>
                                    @Html.TextBoxFor(c => c.FabricName, new { @class = "form-control input-circle", @placeholder = "Fabric Name" })
                                    @Html.ValidationMessageFor(c => c.FabricName)
                                </div>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-3"></div>
                            <div class="col-md-6 text-right">
                                @Html.HiddenFor(c => c.FabricId)
                                <button class="btn btn-success" type="submit"><i class="fa fa-save"></i> Save</button>
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                }
            </div>
        </div>

        <div class="portlet box blue-hoki">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>Fabric Lists
                </div>
                <div class="tools">
                    <a href="javascript:;" class="collapse" data-original-title="" title="">
                    </a>
                </div>
            </div>
            <div class="portlet-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="FabricTable">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Fabric Name</th>
                                <th class="text-center" style="width: 20%">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (fabricModel != null && fabricModel.Count > 0)
                            {
                                int counter = 1;
                                foreach (var data in fabricModel)
                                {
                                    <tr>
                                        <td>@counter</td>
                                        <td>@data.FabricName</td>
                                        <td class="text-center">
                                            @Html.ActionLink(" Edit", "Fabric", "Setup", new { id = data.FabricId }, new { @class = "btn btn-success fa fa-edit" }) ||
                                            @Html.ActionLink(" Delete", "DeleteFabric", "Setup", new { id = data.FabricId }, new { @class = "btn btn-danger fa fa-trash-o" })
                                        </td>
                                    </tr>
                                    counter = counter + 1;
                                }
                            }
                            else
                            {
                                <tr>
                                    <td colspan="3" class="text-center">No Data Found</td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jqueryval")

<script>
    jQuery(document).ready(function () {
        var table = $("#FabricTable").dataTable();
        @{
        if (!string.IsNullOrWhiteSpace(@ViewBag.Message))
        {
        <text>
        var message = '@ViewBag.message';


        toastr.options = {
                    "closeButton": true,
                    "debug": false,
                    "positionClass": "toast-top-center",
                    "onclick": null,
                    "showDuration": "1000",
                    "hideDuration": "1000",
                    "timeOut": "5000",
                    "extendedTimeOut": "1000",
                    "showEasing": "swing",
                    "hideEasing": "linear",
                    "showMethod": "fadeIn",
                    "hideMethod": "fadeOut"
        }
        toastr.info(message, 'Information!');
        </text>
        }
     }
    });

</script>