SaRaEcomAdmin/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using SaRaEcomAdmin.DAL;
using SaRaEcomAdmin.Models;
using SaRaEcomAdmin.Utility;

namespace SaRaEcomAdmin.Controllers
{
    public class ReportController : Controller
    {
        private readonly ReportDocument _objReportDocument = new ReportDocument();
        private ExportFormatType _objExportFormatType = ExportFormatType.NoFormat;
        private readonly ReportDal _objReportDal = new ReportDal();


        public FileStreamResult ShowReport(string pReportType, string pFileDownloadName)
        {

            Response.Buffer = false;
            Response.ClearContent();
            Response.ClearHeaders();
            Response.Clear();
            Response.Buffer = true;



            if (pReportType == "PDF")
            {
                _objExportFormatType = ExportFormatType.PortableDocFormat;

                Stream oStream = _objReportDocument.ExportToStream(_objExportFormatType);
                byte[] byteArray = new byte[oStream.Length];
                oStream.Read(byteArray, 0, Convert.ToInt32(oStream.Length - 1));

                Response.ContentType = "application/pdf";

                pFileDownloadName += ".pdf";

                Response.BinaryWrite(byteArray);
                Response.Flush();
                Response.Close();
                _objReportDocument.Close();
                _objReportDocument.Dispose();

                return File(oStream, Response.ContentType, pFileDownloadName);
            }
            else if (pReportType == "Excel")
            {
                _objExportFormatType = ExportFormatType.Excel;

                Stream oStream = _objReportDocument.ExportToStream(_objExportFormatType);
                byte[] byteArray = new byte[oStream.Length];
                oStream.Read(byteArray, 0, Convert.ToInt32(oStream.Length - 1));

                Response.ContentType = "application/vnd.ms-excel";

                pFileDownloadName += ".xls";

                Response.BinaryWrite(byteArray);
                Response.Flush();
                Response.Close();
                _objReportDocument.Close();
                _objReportDocument.Dispose();

                return File(oStream, Response.ContentType, pFileDownloadName);
            }
            else if (pReportType == "CSV")
            {
                _objExportFormatType = ExportFormatType.CharacterSeparatedValues;

                Stream oStream = _objReportDocument.ExportToStream(_objExportFormatType);
                byte[] byteArray = new byte[oStream.Length];
                oStream.Read(byteArray, 0, Convert.ToInt32(oStream.Length - 1));

                Response.ContentType = "text/csv";

                pFileDownloadName += ".csv";

                Response.BinaryWrite(byteArray);
                Response.Flush();
                Response.Close();
                _objReportDocument.Close();
                _objReportDocument.Dispose();

                return File(oStream, Response.ContentType, pFileDownloadName);
            }
            else if (pReportType == "TXT")
            {
                _objExportFormatType = ExportFormatType.RichText;

                Stream oStream = _objReportDocument.ExportToStream(_objExportFormatType);
                byte[] byteArray = new byte[oStream.Length];
                oStream.Read(byteArray, 0, Convert.ToInt32(oStream.Length - 1));

                Response.ContentType = "text/plain";

                pFileDownloadName += ".txt";

                Response.BinaryWrite(byteArray);
                Response.Flush();
                Response.Close();
                _objReportDocument.Close();
                _objReportDocument.Dispose();

                return File(oStream, Response.ContentType, pFileDownloadName);
            }

            return null;
        }

        private void GenerateSaleReport(ReportModel objSaleReport)
        {
            string strPath = Path.Combine(Server.MapPath("~/Reports/rptSaleHistory.rpt"));
            _objReportDocument.Load(strPath);

            DataSet objDataSet = (_objReportDal.SaleInformation(objSaleReport));


            _objReportDocument.Load(strPath);
            _objReportDocument.SetDataSource(objDataSet);
            _objReportDocument.SetDatabaseLogon("saraecom", "saraecom");

            ShowReport(objSaleReport.ReportType, "Sale Report");
        }

        private void GenerateUploadReport(ReportModel objSaleReport)
        {
            string strPath = Path.Combine(Server.MapPath("~/Reports/rptProductInfoByEmp.rpt"));
            _objReportDocument.Load(strPath);

            DataSet objDataSet = (_objReportDal.ProductInfoByEmployee(objSaleReport));


            _objReportDocument.Load(strPath);
            _objReportDocument.SetDataSource(objDataSet);
            _objReportDocument.SetDatabaseLogon("saraecom", "saraecom");

            ShowReport(objSaleReport.ReportType, "ProductUploadReport");
        }

        private void GenerateCustomerReport(ReportModel model)
        {
            string strPath = Path.Combine(Server.MapPath("~/Reports/rptRegisteredCustomer.rpt"));
            _objReportDocument.Load(strPath);

            DataSet objDataSet = (_objReportDal.RegisteredCustomer());


            _objReportDocument.Load(strPath);
            _objReportDocument.SetDataSource(objDataSet);
            _objReportDocument.SetDatabaseLogon("saraecom", "saraecom");

            ShowReport(model.ReportType, "ProductUploadReport");
        }

        private void GenerateRejectedOrderReport(ReportModel objSaleReport)
        {
            string strPath = Path.Combine(Server.MapPath("~/Reports/rptOrderRejectList.rpt"));
            _objReportDocument.Load(strPath);

            DataSet objDataSet = (_objReportDal.RejectedOrderList(objSaleReport));


            _objReportDocument.Load(strPath);
            _objReportDocument.SetDataSource(objDataSet);
            _objReportDocument.SetDatabaseLogon("saraecom", "saraecom");

            ShowReport(objSaleReport.ReportType, "RejectedOrderReport");
        }

        private void GenerateSuccessOrderRejectedReport(ReportModel objSaleReport)
        {
            string strPath = Path.Combine(Server.MapPath("~/Reports/rptRejectSuccessOrder.rpt"));
            _objReportDocument.Load(strPath);

            DataSet objDataSet = (_objReportDal.RejectedOrderSuccessPaymentList(objSaleReport));


            _objReportDocument.Load(strPath);
            _objReportDocument.SetDataSource(objDataSet);
            _objReportDocument.SetDatabaseLogon("saraecom", "saraecom");

            ShowReport(objSaleReport.ReportType, "RejectedOrderReport");
        }

        public async Task<ActionResult> ViewReport()
        {
            ReportModel model = new ReportModel();

            ViewBag.CategoryList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetCategory(), "CATEGORY_ID", "CATEGORY_NAME");
            ViewBag.MerchandiserList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetMerchandiser(), "EMPLOYEE_ID", "EMPLOYEE_NAME");
            ViewBag.DesignerList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetDesigner(), "EMPLOYEE_ID", "EMPLOYEE_NAME");

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ShowReport(ReportModel model)
        {
            if (model.ReportFor == "1")
            {
                GenerateSaleReport(model);
            }
            else if (model.ReportFor == "2")
            {
                GenerateUploadReport(model);
            }
            else if(model.ReportFor == "3")
            {
                GenerateCustomerReport(model);
            }
            else if (model.ReportFor == "4")
            {
                GenerateRejectedOrderReport(model);
            }
            else if (model.ReportFor == "5")
            {
                GenerateSuccessOrderRejectedReport(model);
            }

            ViewBag.CategoryList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetCategory(), "CATEGORY_ID", "CATEGORY_NAME");
            ViewBag.MerchandiserList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetMerchandiser(), "EMPLOYEE_ID", "EMPLOYEE_NAME");
            ViewBag.DesignerList = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetDesigner(), "EMPLOYEE_ID", "EMPLOYEE_NAME");
            return View("ViewReport", model);
        }

        public async Task<JsonResult> GetSubCategoryList(int categoryId)
        {
            var list = UtilityClass.GetSelectListByDataTable( await _objReportDal.GetSubCategoryList(categoryId), "SUB_CATEGORY_ID", "SUB_CATEGORY_NAME");
            return Json(list, JsonRequestBehavior.AllowGet);
        }
        public async Task<JsonResult> GetSubSubCategoryList(int categoryId, int subCategoryId)
        {
            var list = UtilityClass.GetSelectListByDataTable(await _objReportDal.GetSubSubCategoryList(categoryId, subCategoryId), "SUB_SUB_CATEGORY_ID", "SUB_SUB_CATEGORY_NAME");
            return Json(list, JsonRequestBehavior.AllowGet);
        }
    }
}

SaRaEcomAdmin/Views/Report/ProductUploadByEmployee.cshtml
@model SaRaEcomAdmin.Models.SaleReport
@{
    ViewBag.Title = "SaleReport";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<div class="page-head">
    <div class="page-title">
        <h1>Manage Report</h1>
    </div>
</div>
@using (Html.BeginForm("ProductUploadByEmployee", "Report", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="row margin-top-10">
        <div class="col-md-12">
            <div class="portlet box green-haze">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Report
                    </div>
                    <div class="tools">
                        <span class="pull-right" style="position: relative;">
                            <label>
                                <input type="radio" name="ReportType" value="PDF" checked="checked"> PDF
                            </label> ||
                            <label>
                                <input type="radio" name="ReportType" value="Excel"> Excel
                            </label>
                        </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">

                            <div class="col-md-2">
                                <div class="form-group">
                                    @Html.RadioButtonFor(model => model.ReportFor, "1", new { @checked = true }) Product Upload History
                                </div>
                            </div>
                            <div class="col-md-10">

                                @Html.AntiForgeryToken()
                                <div class="form-body">
                                    <div class="form-group margin-top-15">
                                        @Html.LabelFor(c => c.FormDate, new { @class = "col-md-3 control-label" })
                                        <div class="col-md-6">
                                            <div class="input-icon">
                                                <i class="fa fa-text-width"></i>
                                                @Html.TextBoxFor(c => c.FormDate, new { @class = "form-control input-medium datepicker input-circle", autocomplete = "off", @readonly = "readonly" })
                                                @Html.ValidationMessageFor(c => c.FormDate)
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(c => c.ToDate, new { @class = "col-md-3 control-label" })
                                        <div class="col-md-6">
                                            <div class="input-icon">
                                                <i class="fa fa-text-width"></i>
                                                @Html.TextBoxFor(c => c.ToDate, new { @class = "form-control input-medium datepicker input-circle", autocomplete = "off", @readonly = "readonly" })
                                                @Html.ValidationMessageFor(c => c.ToDate)
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(c => c.CategoryId, new { @class = "col-md-3 control-label" })
                                        <div class="col-md-6">
                                            <div class="input-icon">
                                                <i class="fa fa-text-width"></i>
                                                @Html.DropDownListFor(c => c.CategoryId, new SelectList(ViewBag.CategoryList, "Value", "Text"), new { @class = "form-control input-medium input-circle", @placeholder = "Category Name" })
                                                @Html.ValidationMessageFor(c => c.CategoryId)
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(c => c.SubCategoryId, new { @class = "col-md-3 control-label" })
                                        <div class="col-md-6">
                                            <div class="input-icon">
                                                <i class="fa fa-text-width"></i>
                                                @Html.DropDownListFor(c => c.SubCategoryId, new SelectList(" "), new { @class = "form-control input-medium input-circle", @placeholder = "Sub Category Name", @disabled = true })
                                                @Html.ValidationMessageFor(c => c.SubCategoryId)
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="form-group">
                                        @Html.LabelFor(c => c.SubSubCategoryId, new { @class = "col-md-3 control-label" })
                                        <div class="col-md-6">
                                            <div class="input-icon">
                                                <i class="fa fa-text-width"></i>
                                                @Html.DropDownListFor(c => c.SubSubCategoryId, new SelectList(" "), new { @class = "form-control input-medium input-circle", @placeholder = "Sub Sub Category Name", @disabled = true })
                                                @Html.ValidationMessageFor(c => c.SubSubCategoryId)
                                            </div>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                    <div class="form-group">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-6 text-right">
                                            <button class="btn btn-success" type="submit" formtarget="_blank"><i class="fa fa-save"></i> View</button>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@Scripts.Render("~/bundles/jqueryval")

<script>
    $(function () {
        $(".datepicker").datepicker({
            dateFormat: 'dd/mm/yy'
        });
    });

    jQuery(document).ready(function () {

        $("#CategoryId").change(function () {
            $("#SubCategoryId").empty();
            $("#SubSubCategoryId").empty();
            var catId = $("#CategoryId").val();
            if (!isNaN(catId) && catId) {
                $("#SubCategoryId").prop("disabled", false);
                $("#SubSubCategoryId").prop("disabled", true);
                $.ajax({
                    type: 'POST',
                    url: '/Report/GetSubCategoryList/',
                    dataType: 'json',
                    data: { categoryId: $("#CategoryId").val() },
                    success: function (subCategoryId) {
                        $.each(subCategoryId, function (i, subCategoryId) {
                            $("#SubCategoryId").append('<option value="' + subCategoryId.Value + '">' + subCategoryId.Text + '</option>');
                        });
                    },
                    error: function (ex) { alert('Failed to retrieve Sub Category List.' + ex); }
                });
            } else {
                $("#SubCategoryId").prop("disabled", true);
                $("#SubSubCategoryId").prop("disabled", true);
            }
        });

        $("#SubCategoryId").change(function () {
            $("#SubSubCategoryId").empty();
            var catId = $("#CategoryId").val();
            var subCatId = $("#SubCategoryId").val();
            if (!isNaN(catId) && catId && !isNaN(subCatId) && subCatId) {
                $("#SubSubCategoryId").prop("disabled", false);
                $.ajax({
                    type: 'POST',
                    url: '/Report/GetSubSubCategoryList/',
                    dataType: 'json',
                    data: { categoryId: $("#CategoryId").val(), subCategoryId: $("#SubCategoryId").val() },
                    success: function (subSubCategoryId) {
                        $.each(subSubCategoryId, function (i, subSubCategoryId) {
                            $("#SubSubCategoryId").append('<option value="' + subSubCategoryId.Value + '">' + subSubCategoryId.Text + '</option>');
                        });
                    },
                    error: function (ex) { alert('Failed to retrieve Sub Category List.' + ex); }
                });
            } else {
                $("#SubSubCategoryId").prop("disabled", true);
            }
        });
    });
</script>

SaRaEcomAdmin/Views/Report/RegisteredCustomer.cshtml
@{
    ViewBag.Title = "RegisteredCustomer";
}

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<div class="page-head">
    <div class="page-title">
        <h1>Manage Report</h1>
    </div>
</div>
@using (Html.BeginForm("RegisteredCustomer", "Report", FormMethod.Post, new { @class = "form-horizontal" }))
{
    <div class="row margin-top-10">
        <div class="col-md-12">
            <div class="portlet box green-haze">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-gift"></i>Report
                    </div>
                    <div class="tools">
                        <span class="pull-right" style="position: relative;">
                            <label>
                                <input type="radio" name="ReportType" value="PDF" checked="checked"> PDF
                            </label> ||
                            <label>
                                <input type="radio" name="ReportType" value="Excel"> Excel
                            </label>
                        </span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-10">

                                @Html.AntiForgeryToken()
                                <div class="form-body">
                                    <div class="form-group">
                                        <div class="col-md-3"></div>
                                        <div class="col-md-6 text-right">
                                            <button class="btn btn-success" type="submit" formtarget="_blank"><i class="fa fa-save"></i> View</button>
                                        </div>
                                        <div class="col-md-3"></div>
                                    </div>
                                </div>

                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}