SaRaEcomAdmin/Controllers/MenueController.cs
using System.Threading.Tasks;
using System.Web.Mvc;
using SaRaEcomAdmin.DAL;
using SaRaEcomAdmin.Models;

namespace SaRaEcomAdmin.Controllers
{
    public class MenueController : Controller
    {
        readonly MenuDal _menuDal = new MenuDal();

        public async Task<ActionResult> Index()
        {
            var employee = Session["authentication"] as AuthModel;
            if (employee != null)
            {
                MenuModel menuModel = new MenuModel
                {
                    MenuMains = await _menuDal.GetMenueMain(employee.HeadOfficeId, employee.BranchOfficeId)
                };

                foreach (var menuMain in menuModel.MenuMains)
                {
                    menuMain.MenuSubs =
                        await _menuDal.GetMenueSub(menuMain.MenuId, employee.HeadOfficeId, employee.BranchOfficeId);
                }

                return PartialView("_slidbarPartial", menuModel);
            }
            return null;
        }
    }
}

SaRaEcomAdmin/Views/Shared/_Layout.cshtml
@{
    var employee = Session["authentication"];

    if (employee == null)
    {
        Html.Action("RedirectActionResult","Auth");
    }
}
    
<!DOCTYPE html>
<html lang="en" class="no-js">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title | SaRa Admin Dashboard</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="SaRa LifeStyle" name="description" />
    <meta content="ERP Team" name="author" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css">
    @Styles.Render("~/Content/Assets/css")
    <link href="../../Content/css/components-rounded.css" id="style_components" rel="stylesheet" type="text/css" />
    <link id="style_color" href="../../Content/css/themes/light.css" rel="stylesheet" type="text/css" />
    @Scripts.Render("~/bundles/jquery")

    <link rel="shortcut icon" href="../../favicon.ico" />
</head>

<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
<!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
<!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
<!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
<!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
<!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
<!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
<body class="page-sidebar-closed-hide-logo page-header-fixed page-footer-fixed">
    <!-- BEGIN HEADER -->
    <div class="page-header navbar navbar-fixed-top">
        @*@Html.Action("LoadTopMenue", "Auth")*@
        @{ Html.RenderAction("LoadTopMenue", "Auth"); }
    </div>
    <!-- END HEADER -->
    <div class="clearfix">
    </div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
            @*@Html.Action("Index","Menue")*@
            @{ Html.RenderAction("Index", "Menue"); }
        </div>
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    <div class="page-footer">
        <div class="page-footer-inner">
            &copy; @DateTime.Now.Year - SaRa LifeStyle Ltd.
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
    </div>
    <!-- END FOOTER -->
    @Scripts.Render("~/bundles/script")

<script>
    $(".datepicker").datepicker({
        changeMonth: true,
        changeYear: true,
        dateFormat: "dd/mm/yy"
    });

    jQuery(document).ready(function () {
        Metronic.init(); // init metronic core components
        Layout.init(); // init current layout
        Demo.init(); // init demo features
    });
</script>
    <!-- END JAVASCRIPTS -->
    @RenderSection("scripts", required: false)
</body>
</html>

SaRaEcomAdmin/Views/Shared/_slidbarPartial.cshtml
@using System.Diagnostics
@model SaRaEcomAdmin.Models.MenuModel
<!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
<!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
<div class="page-sidebar navbar-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="false" data-slide-speed="400">
        @*<li class="start"></li>*@
        
    

        @for (int i = 0; i < Model.MenuMains.Count; i++)
        {
            string vliClass;

            if (i == 0)
            {
                vliClass = "start";
            }
            else if (i == Model.MenuMains.Count - 1)
            {
                vliClass = "last";
            }
            else
            {
                vliClass = "";
            }

            <li class="@vliClass" id="@Model.MenuMains[i].MenuId">

                <a href="@Model.MenuMains[i].MenuUrl">
                    <i class="@Model.MenuMains[i].MenuIcon"></i>
                    <span class="title">@Model.MenuMains[i].MenuName</span>
                    @if (Model.MenuMains[i].MenuSubs.Count > 0)
                {
                        <span class="arrow"></span>
                    }
                </a>
                @if (Model.MenuMains[i].MenuSubs.Count > 0)
                {
                    <ul class="sub-menu">
                        @foreach (var subMenu in Model.MenuMains[i].MenuSubs)
                    {
                            <li id="@subMenu.MenuId">
                                <a href="@subMenu.MenuUrl">
                                    <i class="@subMenu.MenuIcon"></i>
                                    @subMenu.MenuName
                                </a>
                            </li>
                        }
                    </ul>
                }

            </li>
        }

    </ul>
    <!-- END SIDEBAR MENU -->
</div>

<script>
    @{
        Debug.Assert(Request.Url != null, "Request.Url != null");
    }
    var uri = "@Request.Url.AbsolutePath";

    $('li > a').each(function () {
        if ($(this).attr('href') === uri) {
            $(this).parents().addClass('active');
        }
    });
</script>